# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_expecie', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Foto_mascota',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('url_foto', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Especie')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('raza', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='id_raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Raza'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foto_mascota',
            name='id_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Mascota'),
        ),
    ]
