# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_auto_20170228_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='rescatista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL),
        ),
    ]
